# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev15+g5bc8782.d20220715'
__version_tuple__ = version_tuple = (0, 1, 'dev15', 'g5bc8782.d20220715')
